name: Deploy Jekyll Documentation
on:
  push:
      branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: List files in _site directory
        run: |
          echo "Contenu du répertoire _site:"
          ls -la _site || echo "Le répertoire _site n'existe pas!"
          echo "Répertoire courant: $(pwd)"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs/_site
          retention-days: 1
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
      actions: read
    steps:
        - name: Déployer
          id: deployment
          uses: actions/deploy-pages@v4 # Version critique
          with:
            token: ${{ secrets.GITHUB_TOKEN }}